config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  
  mount ShoppingCart::Engine => '', as: 'shopping_cart'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :books, only: [:show] do
    get '(category-:category)', action: :index, on: :collection, as: ''
    resources :reviews, only: [:create]
  end

  namespace :users do
    resources :orders, only: [:show] do
      get '(status/:status)', action: :index, on: :collection, as: ''
    end
  end

  devise_for :users,
              controllers: {
                registrations: 'users/registrations',
                omniauth_callbacks: 'users/omniauth_callbacks'
              },
              path_names: {
                sign_in:  'log_in',
                sign_out: 'log_out',
                edit:     'settings'
              }

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @latest_books = Book.includes(:authors).latest(3).decorate
    @best_sellers = BestSellers.new.query.decorate
  end
end

app/views/home/_best_seller.html.haml
.col-sm-6.col-md-3
  .general-thumb-wrap
    .thumbnail.general-thumbnail{ class: book.disabled_class }
      = image_tag book.cover.thumb.url, class: 'img-shadow general-thumbnail-img' 
      .thumb-hover
        .general-thumb-link-wrap
          = link_to book_path(book), class: 'thumb-hover-link' do
            %i.fa.fa-eye.thumb-icon{ 'aria-hidden' => 'true' }
            
          = form_for :order_item, url: shopping_cart.order_items_path do |form|
            = hidden_field_tag 'order_item[quantity]', 1
            = hidden_field_tag 'order_item[product_id]', book.id
            = hidden_field_tag 'order_item[product_type]', book.object.class
            = form.button class: 'thumb-hover-link' do
              %i.fa.fa-shopping-cart.thumb-icon{ 'aria-hidden' => 'true' }
  .mb-35
    .clearfix
      %p.pull-right.font-16.in-gold-500= book.formatted_price
      %p.title.mr-55= book.title
    %span.divider-sm
    %p.lead.small= book.joined_authors

app/views/home/_best_sellers.html.haml
%h3= t('home.best_sellers')
.row
  = render partial: 'best_seller', collection: @best_sellers, as: :book

app/views/home/_carousel_indicator.html.haml
%li{ class: ('active' if book_iteration.first?), data: { 'target' => '#slider', 'slide-to' => book_iteration.index } }

app/views/home/_latest_book.html.haml
.item{ class: ('active' if book_iteration.first?) }
  .row
    .col-sm-5
      .general-img-wrap
        = image_tag book.cover.url, class: 'img-shadow general-thumbnail-img'
    .col-sm-7
      .mb-60
        %h1= book.title
        %p.lead= book.more_short_description
        %p.lead.small= book.joined_authors
        .general-align
          = form_for :order_item, url: shopping_cart.order_items_path do |form|
            = hidden_field_tag 'order_item[quantity]', 1
            = hidden_field_tag 'order_item[product_id]', book.id
            = hidden_field_tag 'order_item[product_type]', book.object.class
            = form.button t('home.buy_now'), class: "#{book.btn_class} btn", disabled: !book.in_stock?

app/views/home/_latest_books.html.haml
#slider.carousel.slide{ 'data-ride' => 'carousel' }
  %ol.carousel-indicators
    = render partial: 'carousel_indicator', collection: @latest_books, as: :book

  .carousel-inner{role: 'listbox'}
    = render partial: 'latest_book', collection: @latest_books, as: :book

  %a.left.carousel-control{ href: '#slider', role: 'button', 'data-slide' => 'prev' }
    %span.icon-prev{ 'aria-hidden' => 'true' }
    %span.sr-only Previous

  %a.right.carousel-control{ href: '#slider', role: 'button', 'data-slide' => 'next' }
    %span.icon-next{ 'aria-hidden' => 'true' }
    %span.sr-only Next

app/views/home/index.html.haml
%main.container
  = render 'latest_books'
.container
  .jumbotron.text-center.mb-0
    %h2.h1= t('home.welcome')
    .mb-res-50
      %p= t('home.text')
    = link_to t('home.get_started'), books_path, class: 'btn btn-default'
  .mb-35
    = render 'best_sellers'