config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  
  mount ShoppingCart::Engine => '', as: 'shopping_cart'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :books, only: [:show] do
    get '(category-:category)', action: :index, on: :collection, as: ''
    resources :reviews, only: [:create]
  end

  namespace :users do
    resources :orders, only: [:show] do
      get '(status/:status)', action: :index, on: :collection, as: ''
    end
  end

  devise_for :users,
              controllers: {
                registrations: 'users/registrations',
                omniauth_callbacks: 'users/omniauth_callbacks'
              },
              path_names: {
                sign_in:  'log_in',
                sign_out: 'log_out',
                edit:     'settings'
              }

  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_one :billing_address,  as: :addressable, dependent: :destroy, class_name: 'ShoppingCart::BillingAddress'
  has_one :shipping_address, as: :addressable, dependent: :destroy, class_name: 'ShoppingCart::ShippingAddress'

  has_many :reviews, dependent: :destroy
  has_many :orders,  dependent: :nullify, class_name: 'ShoppingCart::Order'

  validates_with PasswordValidator, if: :password_required?

  accepts_nested_attributes_for :billing_address, :shipping_address

  devise :database_authenticatable,
         :registerable,
         :rememberable,
         :confirmable,
         :recoverable,
         :validatable,
         :omniauthable,
         omniauth_providers: [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email      = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name  = auth.info.last_name
      user.avatar     = auth.info.image

      user.skip_confirmation!
      user.skip_password_validations!
    end
  end

  def skip_password_validations!
    self.password = Devise.friendly_token
    @skip_validations = true
  end

  def skip_password_validations?
    !!@skip_validations
  end

  private

  def password_required?
    return false if skip_password_validations?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
  before_action :authenticate_user!
  
  load_resource only: [:index], class: 'ShoppingCart::Order'

  def index
    @orders = FilterOrders.new(@orders, params[:status]).query.decorate
  end

  def show
    @order = ShoppingCart::Order.for_show.find(params[:id]).decorate
    authorize! :show, @order.object
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super { render :quick_new and return if params[:type] == 'quick' }
  end

  # POST /resource
  def create
    super do |resource|
      if params[:quick_sign_up] == 'true'
        resource.skip_password_validations!
        unless resource.save
          flash[:alert] = t('.wrong_email')
          redirect_to new_user_registration_path(type: :quick) and return
        end
      end
    end
  end

  # DELETE /resource
  def destroy
    if params[:destroying_confirmation]
      super
    else
      redirect_to edit_user_registration_path, alert: t('.confirm_destroying')
    end
  end

  protected

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [
      billing_address_attributes:  Address::FIELDS,
      shipping_address_attributes: Address::FIELDS
    ])
  end

  def update_resource(resource, params)
    if params[:password].present?
      resource.update_with_password(params)
    else
      resource.update_without_password(params)
    end
  end

  def after_update_path_for(_resource)
    edit_user_registration_path
  end

  def after_sign_up_path_for(resource)
    if params[:quick_sign_up] == 'true'
      checkout_index_path
    else
      after_sign_in_path_for(resource)
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def active_filter
    status = params[:status]
    return status if FilterOrders::ALLOWED_STATUSES.include?(status)
    FilterOrders::ALLOWED_STATUSES.first
  end
end

app/views/users/orders/_hidden_xs.html.haml
.hidden-xs.mb-res-50
  %table.table.table-hover
    %thead
      %tr
        %th
          %span.in-grey-600= t('orders.number')
        %th
          %span.in-grey-600= t('orders.completed_at')
        %th
          %span.in-grey-600= t('orders.status')
        %th
          %span.in-grey-600= t('orders.total')
    %tbody
      = render partial: 'order', collection: @orders, as: :order

app/views/users/orders/_order.html.haml
%tr
  %td
    = link_to users_order_path(order) do
      %span.general-order-number= order.number
  %td
    %span.in-grey-900.font-16.fw-300= order.formatted_completed_at
  %td
    %span.font-16.in-grey-900.fw-300= order.status
  %td
    %strong.font-16= order.formatted_total

app/views/users/orders/_order_xs.html.haml
.general-cart-item{ class: ('divider-lg-bottom pt-0' unless order_iteration.last?) }
  %table.table
    %tr
      %td.col-half
        %span.in-grey-600= t('orders.number')
      %td.col-half
        = link_to users_order_path(order) do
          %span.general-order-number= order.number
    %tr
      %td
        %span.in-grey-600= t('orders.completed_at')
      %td
        %span.in-grey-900.font-16.fw-300= order.formatted_completed_at
    %tr
      %td
        %span.in-grey-600= t('orders.status')
      %td
        %span.font-16.fw-300.text-alert= order.status
    %tr
      %td
        %span.in-grey-600= t('orders.total')
      %td
        %strong.font-16= order.formatted_total

app/views/users/orders/_status_list.html.haml
- content_for :active, t(active_filter, scope: 'orders_filters'), flush: true

- FilterOrders::ALLOWED_STATUSES.each do |status|
  %li
    = link_to t(status, scope: 'orders_filters'), users_orders_path(status: status)

app/views/users/orders/index.html.haml
%main.container.general-main-wrap
  %h1.mt-0.mb-25= t('orders.my_orders')
  %p.lead.small.mb-10.visible-xs= t('orders.filter_by')
  .dropdowns.dropdown.general-order-dropdown
    = render partial: 'status_list', layout: 'shared/dropdown'

  - if @orders.present?
    .visible-xs
      = render partial: 'order_xs', collection: @orders, as: :order

    = render 'hidden_xs'
    
  - else
    .text-center= t('orders.no_orders')

app/views/users/orders/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin= @order.number
  .row.mb-20
    - [:shipping_address, :billing_address].each do |type|
      .col-sm-3
        %h3.general-subtitle.mt-0= t(type)
        = render 'shared/address', address: @order.send(type)

    .col-sm-3
      - delivery = @order.shipping_method
      %h3.general-subtitle.mt-0= t('shipments')
      %p.general-address
        = delivery.name
        %br
        = delivery.days
        %br
        = delivery.formatted_price

    .col-sm-3
      - payment = @order.credit_card
      %h3.general-subtitle.mt-0= t('payment_info')
      %p.general-address
        = payment.formatted_number
        %br
        = payment.month_year

  = render 'shared/items'

  = render 'shared/summary', class: 'text-center general-text-right',
                             table_class: 'general-summary-table-right general-text-right',
                             order: @order