config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  
  mount ShoppingCart::Engine => '', as: 'shopping_cart'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :books, only: [:show] do
    get '(category-:category)', action: :index, on: :collection, as: ''
    resources :reviews, only: [:create]
  end

  namespace :users do
    resources :orders, only: [:show] do
      get '(status/:status)', action: :index, on: :collection, as: ''
    end
  end

  devise_for :users,
              controllers: {
                registrations: 'users/registrations',
                omniauth_callbacks: 'users/omniauth_callbacks'
              },
              path_names: {
                sign_in:  'log_in',
                sign_out: 'log_out',
                edit:     'settings'
              }

  root 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ShoppingCart::Controllers::OrderHelpers
  
  protect_from_forgery with: :exception

  before_action :set_locale

  helper_method :categories

  rescue_from CanCan::AccessDenied do
    redirect_back(fallback_location: root_path, alert: t('denied'))
  end

  private

  def categories
    @categories ||= Category.all
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end
end

app/views/application/_account_options.html.haml
- content_for :title, t('application.my_account'), flush: true

- content_for :additional_options, flush: true do
  %li.divider{ role: 'separator' }
  = content_for :log_out_link

%li
  = link_to t('application.orders'), main_app.users_orders_path, class: local_assigns[:link_class]

%li
  = link_to t('application.settings'), edit_registration_path(:user), class: local_assigns[:link_class]

app/views/application/_cart.html.haml
= link_to shopping_cart.cart_path, class: "#{xs}-xs shop-link pull-right" do
  %span.shop-icon{ class: ('empty' if current_order.total_quantity.zero?) }
    - unless current_order.total_quantity.zero?
      %span.shop-quantity= current_order.total_quantity

app/views/application/_collapse.html.haml
%li
  %a{ type: 'button', 'data-toggle' => 'collapse', href: "##{id}-menu", 'aria-expanded' => 'false', 'aria-controls' => 'account-menu' }
    = content_for :title
  %ul.collapse.list-unstyled.pl-30.mb-10{'aria-expanded' => 'false', id: "#{id}-menu" }
    = yield 

app/views/application/_dropdown.html.haml
%li.dropdown
  %a.dropdown-toggle{ href: '#', 'data-toggle' => 'dropdown', role: 'button', 'aria-haspopup' => 'true', 'aria-expanded' => 'false' }
    = content_for :title
  %ul.dropdown-menu
    = yield
    = content_for :additional_options

app/views/application/_flashes.html.haml
- if flash.any?
  .container
    - if notice
      .alert.alert-info.alert-dismissable.fade.in
        %a.close{ 'aria-label' => 'close', 'data-dismiss' => 'alert', href: '#' } &times;
        = notice
    - if alert
      .alert.alert-danger.alert-dismissable.fade.in
        %a.close{ 'aria-label' => 'close', 'data-dismiss' => 'alert', href: '#' } &times;
        = alert

app/views/application/_footer.html.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            = link_to t('application.home'), main_app.root_path, class: 'nav-link'
          %li
            = link_to t('application.shop'), main_app.books_path, class: 'nav-link'
          - if user_signed_in?
            = render 'account_options', link_class: 'nav-link'
      .col-sm-3
        %p.general-nav-mail support@bookstore.com
        %p.general-nav-number (555)-555-5555
        %ul.list-inline.general-align
          - ['facebook', 'twitter', 'google-plus', 'instagram'].each do |social|
            %li
              %a.nav-link{ href: '#' }
                %i.fa{ class: "fa-#{social}", 'aria-hidden' => 'true' }

app/views/application/_header.html.haml
- content_for :log_out_link do
  %li
    = link_to t('application.log_out'), destroy_session_path(:user), method: :delete

- content_for :auth_links do
  %li
    = link_to t('application.log_in'), new_session_path(:user)
  %li
    = link_to t('application.sign_up'), new_registration_path(:user)

%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{ type: 'button', 'data-toggle' => 'collapse', 'data-target' => '#navbar' }
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Bookstore', main_app.root_path, class: 'navbar-brand'
      = render 'cart', xs: 'visible'
    = render 'cart', xs: 'hidden'
    #navbar.navbar-collapse.collapse.pl-30{ 'aria-expanded' => 'false' }
      = render 'navbar_xs_visible'
      = render 'navbar_xs_hidden'

app/views/application/_navbar_xs_hidden.html.haml
.hidden-xs
  %ul.nav.navbar-nav
    %li
      = link_to 'en', url_for(locale: :en), class: 'language-link'
      = '/'
      = link_to 'ru', url_for(locale: :ru), class: 'language-link'
    %li
      = link_to t('application.home'), main_app.root_path
    = render partial: 'shop_options', layout: 'application/dropdown'

    - if user_signed_in?
      = render partial: 'account_options', layout: 'application/dropdown'
    - else
      = content_for :auth_links

app/views/application/_navbar_xs_visible.html.haml
.visible-xs
  %ul.nav.navbar-nav
    %li
      = link_to 'en', url_for(locale: :en), class: 'language-link'
      = '/'
      = link_to 'ru', url_for(locale: :ru), class: 'language-link'
    %li
      = link_to t('application.home'), main_app.root_path
    = render partial: 'shop_options', layout: 'collapse', locals: { id: 'shop', link_class: 'collapse-link' }

    - if user_signed_in?
      = render partial: 'account_options', layout: 'collapse', locals: { id: 'account', link_class: 'collapse-link' }
      = content_for :log_out_link
    - else
      = content_for :auth_links

app/views/application/_shop_options.html.haml
- content_for :title, t('application.shop'), flush: true

- content_for :additional_options, '', flush: true

%li
  = link_to t('categories.all'), main_app.books_path, class: local_assigns[:link_class]
- categories.each do |category|
  %li
    = link_to category.name, main_app.books_path(category), class: local_assigns[:link_class]